"Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
syntax on
set nocompatible
set undolevels=1000
set history=50
set ruler
set backspace=indent,eol,start
set showmatch
set ignorecase
set hlsearch
set incsearch
set vb t_vb=
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set number
set mouse=a
syntax enable
colorscheme molokai
set t_Co=256
let g:airline_theme='molokai'
"let g:molokai_original = 1
"let g:rehash256 = 1
let NERDTreeShowHidden=1
set backupdir=~/.vim/backup_files//
set directory=~/.vim/swap_files//
set undodir=~/.vim/undo_files//
autocmd vimenter * NERDTree
autocmd FileType python setlocal colorcolumn=80
autocmd FileType python setlocal tabstop=4
autocmd FileType python setlocal softtabstop=4
autocmd FileType python setlocal shiftwidth=4
highlight ColorColumn ctermbg=7
set backupcopy=yes

"Don't unselect block after indent/outdent
vnoremap < <gv
vnoremap > >gv

"Splitting options
set splitbelow
set splitright

"Command aliases
command WQ wq
command Wq wq
command W w
command Q q

"Set window title to filename
set title

"Status bar options
set showcmd
set laststatus=2
