"Pathogen
runtime bundle/vim-pathogen/autoload/pathogen.vim
execute pathogen#infect()
syntax on
filetype plugin indent on
set nocompatible
set undolevels=1000
set history=50
set ruler
set backspace=indent,eol,start
set showmatch
set ignorecase
set hlsearch
set incsearch
set vb t_vb=
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smarttab
set number
set mouse=a
syntax enable
colorscheme molokai
set t_Co=256
let g:airline_theme='molokai'
"let g:molokai_original = 1
"let g:rehash256 = 1
let NERDTreeShowHidden=1
set backupdir=~/.vim/backup_files//
set directory=~/.vim/swap_files//
set undodir=~/.vim/undo_files//
autocmd vimenter * NERDTree
autocmd FileType python setlocal colorcolumn=80
autocmd FileType python setlocal tabstop=4
autocmd FileType python setlocal softtabstop=4
autocmd FileType python setlocal shiftwidth=4
highlight ColorColumn ctermbg=7
set backupcopy=yes

"Don't unselect block after indent/outdent
vnoremap < <gv
vnoremap > >gv

"Splitting options
set splitbelow
set splitright

"Command aliases
command WQ wq
command Wq wq
command W w
command Q q

"Set window title to filename
set title

"Status bar options
set showcmd
set laststatus=2

"Typescript setup
let g:typescript_compiler_binary = 'tsc'
let g:typescript_compiler_options = ''
autocmd QuickFixCmdPost [^l]* nested cwindow
autocmd QuickFixCmdPost    l* nested lwindow

autocmd FileType typescript JsPreTmpl html
autocmd FileType typescript syn clear foldBraces

"Syntastic Configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:tsuquyomi_disable_quickfix = 0
let g:syntastic_typescript_checkers = ['tsuquyomi']

"editorconfig settings
let g:EditorConfig_core_mode = 'external_command'
"let g:EditorConfig_verbose=1

"Airline setup
let g:airline_powerline_fonts = 1

if !exists('g:airline_symbols')
    let g:airline_symbols = {}
endif

" unicode symbols
let g:airline_left_sep = '»'
let g:airline_left_sep = '▶'
let g:airline_right_sep = '«'
let g:airline_right_sep = '◀'
let g:airline_symbols.linenr = '␊'
let g:airline_symbols.linenr = '␤'
let g:airline_symbols.linenr = '¶'
let g:airline_symbols.branch = '⎇'
let g:airline_symbols.paste = 'ρ'
let g:airline_symbols.paste = 'Þ'
let g:airline_symbols.paste = '∥'
let g:airline_symbols.whitespace = 'Ξ'

" airline symbols
let g:airline_left_sep = ''
let g:airline_left_alt_sep = ''
let g:airline_right_sep = ''
let g:airline_right_alt_sep = ''
let g:airline_symbols.branch = ''
let g:airline_symbols.readonly = ''
let g:airline_symbols.linenr = ''

"Add vimproc.vim lib/ dir to runtimepath
"set runtimepathr^+=lib/
let g:tsuquyomi_auto_open=1
let g:tsuquyomi_definition_split=2
