[[ -e ~/.profile ]] && source ~/.profile    # load generic profile settings
export PATH="/usr/local/opt/mysql-client/bin:$PATH"

export PATH="$HOME/.poetry/bin:$PATH"
export PATH="/usr/local/opt/openjdk/bin:$PATH"
export PATH="/usr/local/opt/openjdk@8/bin:$PATH"
export PATH="/usr/local/opt/libxml2/bin:$PATH"
alias vpn='/Users/mike.conroy/vpn'
