
# Set user bash scripts path
export PATH=/Users/michael/bin/:$PATH

# Handle Java Installations
export JAVA_HOME_8=$(/usr/libexec/java_home -v1.8)
export JAVA_HOME_11=$(/usr/libexec/java_home -v12)

export JAVA_HOME=$JAVA_HOME_8

# Add MySQL to path
export PATH=/usr/local/mysql/bin/:$PATH

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=100000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# set a fancy prompt (non-color, unless we know we "want" color)
PS1='\[\e[35m\]\t\[\e[m\] \[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] \$ '

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [[ "$OSTYPE" == "darwin"*  ]]; then
  alias ls='ls -G'
elif [[ "$OSTYPE" == "linux"*  ]]; then
  alias ls='ls --color=auto'
fi
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# some more ls aliases
alias ll='ls -Flash'
#alias la='ls -A'
#alias l='ls -CF'

# git aliases
alias gitlog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.bash_aliases, instead of adding them here directly.
# See /usr/share/doc/bash-doc/examples in the bash-doc package.

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
# if ! shopt -oq posix; then
#   if [ -f /usr/share/bash-completion/bash_completion ]; then
#     . /usr/share/bash-completion/bash_completion
#   elif [ -f /etc/bash_completion ]; then
#     . /etc/bash_completion
#   fi
# fi

# ENABLE ALL THE COLORS!
export TERM='xterm-color'

# export NVM_DIR="/Users/michael/.nvm"
# [[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"  # This loads nvm

# export PATH="$HOME/.yarn/bin:$PATH"
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Homebrew bash completion
# if [ -f $(brew --prefix)/etc/bash_completion ]; then
#   . $(brew --prefix)/etc/bash_completion
# fi

# Nexus Configuration
set -o allexport
source ~/.nexus
set +o allexport
NEXUS_INDEX_URL="https://$NEXUS_PULL_USER:$NEXUS_PULL_PASS@artifacts.dox.support/repository/python/simple"
PIP_INDEX_URL="https://$NEXUS_PULL_USER:$NEXUS_PULL_PASS@artifacts.dox.support/repository/python/simple"

# Snowflake COnfiguration
set -o allexport
source ~/.snowflake
set +o allexport

# Open file in Sublime Text
alias sub="open -t"
alias sublime="open -t"

# virtualenvwrapper Configuration
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/dev
export VIRTUALENVWRAPPER_PYTHON=/Users/michael/.pyenv/shims/python
source /Users/michael/.pyenv/versions/3.7.9/bin/virtualenvwrapper.sh

# OpenSSL Compiler Flags and Path
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

# For enhanced Mortar functionality, including creating new clusters
export MORTAR_SUDO=TRUE

# For ScaleFT/ASA
export SCALEFT_ENABLED=true

export PATH=/usr/local/bin:/usr/local/sbin:$PATH


# Init pyenv
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

export MORTAR_AWS_VAULT_PROFILE='dox-data-dev'



